/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibeRouteImport } from './routes/vibe'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartyRouteImport } from './routes/party'
import { Route as GenreRouteImport } from './routes/genre'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartySessionIdRouteImport } from './routes/party_.$sessionId'
import { Route as PartySessionIdResultsRouteImport } from './routes/party_.$sessionId_.results'
import { Route as PartySessionIdPreferencesRouteImport } from './routes/party_.$sessionId_.preferences'

const VibeRoute = VibeRouteImport.update({
  id: '/vibe',
  path: '/vibe',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyRoute = PartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreRoute = GenreRouteImport.update({
  id: '/genre',
  path: '/genre',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartySessionIdRoute = PartySessionIdRouteImport.update({
  id: '/party_/$sessionId',
  path: '/party/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartySessionIdResultsRoute = PartySessionIdResultsRouteImport.update({
  id: '/party_/$sessionId_/results',
  path: '/party/$sessionId/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PartySessionIdPreferencesRoute =
  PartySessionIdPreferencesRouteImport.update({
    id: '/party_/$sessionId_/preferences',
    path: '/party/$sessionId/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genre': typeof GenreRoute
  '/party': typeof PartyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/vibe': typeof VibeRoute
  '/party/$sessionId': typeof PartySessionIdRoute
  '/party/$sessionId/preferences': typeof PartySessionIdPreferencesRoute
  '/party/$sessionId/results': typeof PartySessionIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genre': typeof GenreRoute
  '/party': typeof PartyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/vibe': typeof VibeRoute
  '/party/$sessionId': typeof PartySessionIdRoute
  '/party/$sessionId/preferences': typeof PartySessionIdPreferencesRoute
  '/party/$sessionId/results': typeof PartySessionIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/genre': typeof GenreRoute
  '/party': typeof PartyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topics': typeof TopicsRoute
  '/vibe': typeof VibeRoute
  '/party_/$sessionId': typeof PartySessionIdRoute
  '/party_/$sessionId_/preferences': typeof PartySessionIdPreferencesRoute
  '/party_/$sessionId_/results': typeof PartySessionIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genre'
    | '/party'
    | '/sitemap.xml'
    | '/topics'
    | '/vibe'
    | '/party/$sessionId'
    | '/party/$sessionId/preferences'
    | '/party/$sessionId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genre'
    | '/party'
    | '/sitemap.xml'
    | '/topics'
    | '/vibe'
    | '/party/$sessionId'
    | '/party/$sessionId/preferences'
    | '/party/$sessionId/results'
  id:
    | '__root__'
    | '/'
    | '/genre'
    | '/party'
    | '/sitemap.xml'
    | '/topics'
    | '/vibe'
    | '/party_/$sessionId'
    | '/party_/$sessionId_/preferences'
    | '/party_/$sessionId_/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenreRoute: typeof GenreRoute
  PartyRoute: typeof PartyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopicsRoute: typeof TopicsRoute
  VibeRoute: typeof VibeRoute
  PartySessionIdRoute: typeof PartySessionIdRoute
  PartySessionIdPreferencesRoute: typeof PartySessionIdPreferencesRoute
  PartySessionIdResultsRoute: typeof PartySessionIdResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibe': {
      id: '/vibe'
      path: '/vibe'
      fullPath: '/vibe'
      preLoaderRoute: typeof VibeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre': {
      id: '/genre'
      path: '/genre'
      fullPath: '/genre'
      preLoaderRoute: typeof GenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$sessionId': {
      id: '/party_/$sessionId'
      path: '/party/$sessionId'
      fullPath: '/party/$sessionId'
      preLoaderRoute: typeof PartySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$sessionId_/results': {
      id: '/party_/$sessionId_/results'
      path: '/party/$sessionId/results'
      fullPath: '/party/$sessionId/results'
      preLoaderRoute: typeof PartySessionIdResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party_/$sessionId_/preferences': {
      id: '/party_/$sessionId_/preferences'
      path: '/party/$sessionId/preferences'
      fullPath: '/party/$sessionId/preferences'
      preLoaderRoute: typeof PartySessionIdPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenreRoute: GenreRoute,
  PartyRoute: PartyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopicsRoute: TopicsRoute,
  VibeRoute: VibeRoute,
  PartySessionIdRoute: PartySessionIdRoute,
  PartySessionIdPreferencesRoute: PartySessionIdPreferencesRoute,
  PartySessionIdResultsRoute: PartySessionIdResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
